language: java
jdk:
  - openjdk8
services:
  - docker
#For caching the mvn repo
cache:
  directories:
  - .autoconf
  - $HOME/.m2
#mvn build
script: 
  - ./mvnw clean install
  - docker build -t hasanalam/myrepo .
  - docker push hasanalam/myrepo
