language: java
jdk:
  - openjdk8
services:
  - docker
#For caching the mvn repo
cache:
  directories:
  - .autoconf
  - $HOME/.m2
#mvn build
script: 
  - ./mvnw clean install
  - export TAG = TCI$(date +'%Y%m%d%H%M%S')
  - docker build -t hasanalam/myrepo:$TAG .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push hasanalam/myrepo:$TAG
