language: java
jdk:
  - openjdk8
services:
  - docker
env:
  - TRAVIS_TAG = LATESTV
#For caching the mvn repo
cache:
  directories:
  - .autoconf
  - $HOME/.m2
#mvn build
script: 
  - ./mvnw clean install
  - $TRAVIS_TAG=TCI${date +'%Y%m%d%H%M%S'}
  - echo "============Travis Tag#$TRAVIS_TAG"
  - docker build -t hasanalam/myrepo:$TRAVIS_TAG .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push hasanalam/myrepo:$TRAVIS_TAG
