# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload output jar file
        uses: actions/upload-artifact@v1
        with:
          name: demo
          path: target/demo-0.0.1-SNAPSHOT.jar
      - name: Upload docker file
        uses: actions/upload-artifact@v1
        with:
          name: Dockerfile
          path: Dockerfile    
  dockerize:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: demo
      - name: Download Dockerfile
        uses: actions/download-artifact@v2
        with:
          name: Dockerfile    
      - name: Build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: hasanalam/myrepo
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      